<?php
/**
 * @author Saqqal Abdelaziz <seqqal.abdelaziz@gmail.com>
 * @Linkedin https://www.linkedin.com/abdelaziz-saqqal
 */

namespace Saqqal\LlmIntegrationBundle\Services;

use Saqqal\LlmIntegrationBundle\Interface\AiClientInterface;
use Saqqal\LlmIntegrationBundle\Interface\AiServiceInterface;
use Saqqal\LlmIntegrationBundle\Response\AiResponse;

class AiService implements AiServiceInterface
{
    /**
     * Constructor for the ApiTogetherService class.
     *
     * @param AiClientInterface $client The AI client to interact with the API Together service.
     * @param string $model The default model to use for generating AI responses.
     * @param string $provider
     */
    public function __construct(
        private readonly AiClientInterface $client,
        private string $model,
        private readonly string $provider
    ) {
    }

    /**
     * Generates an AI response based on the provided prompt and options.
     *
     * @param string $prompt The input prompt for the AI model.
     * @param array $options Additional options for generating the AI response.
     * @return AiResponse The AI response generated by the API Together service.
     */
    public function generate(string $prompt, array $options = [], bool $dynamicResponse = false): mixed
    {
        $model = $options['model'] ?? $this->model;
        return $this->client->sendPrompt($prompt, $model, $dynamicResponse);
    }

    /**
     * Returns the name of the AI service provider.
     *
     * @return string The name of the AI service provider.
     */
    public function getProviderName(): string
    {
        return ucfirst($this->provider);
    }

    /**
     * Returns the current model being used for generating AI responses.
     *
     * @return string The current model being used.
     */
    public function getCurrentModel(): string
    {
        return $this->model;
    }

    /**
     * Sets the model to be used for generating AI responses.
     *
     * @param string $model The model to be used for generating AI responses.
     */
    public function setModel(string $model): void
    {
        $this->model = $model;
    }
}
