services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Saqqal\LlmIntegrationBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../Kernel.php'

  Saqqal\LlmIntegrationBundle\EventSubscriber\LlmIntegrationExceptionSubscriber:
    arguments:
      $logger: '@logger'
    tags:
      - { name: kernel.event_subscriber }