<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    return;
}

require dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor/autoload.php';
(require __DIR__.'/Symfony_Component_HttpKernel_KernelQrsoSs8TestDebugContainer.php')->set(\ContainerBE9xdLy\Symfony_Component_HttpKernel_KernelQrsoSs8TestDebugContainer::class, null);

$classes = [];
$classes[] = 'Saqqal\LlmIntegrationBundle\LlmIntegrationBundle';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

$preloaded = Preloader::preload($classes);
